replicaCount: 1

config:
  superSecret:
    name: super-secret-name
  notSoSecret: not-so-secret-value

serviceAccount:
  create: true

valueFromSecret:
  secretName: super-secret-name
  key: value

valueFromModuleVariable: module-variable-value

valueFromEnvironmentConfig: environment-config-value

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
